### ISSUE TITLE
Property.findSeparator is scanning strings character-by-character

### ISSUE THREAD

**Issue by InPermutation** [Avansai/properties-file#19]
Related to #16 #17 #18 - `findSeparator` is also showing up in my profiler as a significant CPU user; I think it can be significantly sped up by using e.g. 

```
for (const match of this.linesContent[0].matchAll(/[\t\f :=]/g)) {
  if (!match.index) { continue; }

  const position = match?.index
```

but I haven't finished drafting the PR, so I'm filing this Issue instead 😎

**Comment by nbouvrette** [comment]
@InPermutation the fix is now available in [3.3.2](https://github.com/Avansai/properties-file/releases/tag/3.3.2)

Let me know if you see anything I might have missed.
