### ISSUE TITLE
Serializing back to properties file? 

### ISSUE THREAD

**Issue by tappleby** [Avansai/properties-file#2]
Thanks for the great library! I have been looking into possibly using this package in an application that needs to modify values in a properties file and write it back to disk, curious if there's any plans to support this?

If not perhaps adding an `endingLineNumber` to the property could help with implementing this externally.

**Comment by nbouvrette** [comment]
Thanks @tappleby - sorry for the late reply.

Regarding writing back to disk, I think that it could be done with something like this:

```ts
import fs from 'node:fs'
import { EOL } from 'node:os'

const properties = getProperties('assets/tests/collisions-test.properties')
const newProperties: string[] = []

properties.collection.forEach((property) => {
  const value = property.value === 'world3' ? 'new world3' : property.value
  newProperties.push(`${property.key} : ${value}`)
})

fs.writeFileSync('myNewFile.properties', newProperties.join(EOL))
```

Of course, this would not cover cases where you would need to escape characters and we only have `unescape` methods available right now.

But I don't have all the details of what you are trying to achieve so I am just guessing here.

**Comment by nbouvrette** [comment]
@tappleby I don't know if you still need this, but you can thank @mdvorak for implementing escape functions.

Those new APIs are available in version [2.2.0](https://github.com/Avansai/properties-file/releases/tag/2.2.0). You can see an up-to-date example of how to serialize back to `.properties` format in the main [readme](https://github.com/Avansai/properties-file#readme) file.

I will be closing this issue. If you have other use cases that are not covered by these new APIs, feel free to open a new issue.

**Comment by mdvorak** [comment]
I've ended up finishing my own library (I know, another one), which focuses primary on modification of properties files. I've had it mostly written for some time now, I just kinda did not want to maintain it :-)

If anyone is interested:
https://www.npmjs.com/package/js-java-properties

@nbouvrette I've used your example properties file to improve my tests, thank you for that

**Comment by nbouvrette** [comment]
@mdvorak nice package - I like how you handled some of the parsing logic.

If you get tired of maintaining it we could always see if we could merge some of the functionalities. In fact, I think it wouldn't be too complicated to add better properties modification APIs, and might take a stab at it today to see how much effort it would take.

**Comment by tappleby** [comment]
I got busy just after opening this PR, only just getting caught up now :) 

My main use-case was our application has a UI to edit some locale and other configuration files, not all formatting needs to be maintained but preserving comments is important. It looks like @mdvorak package handles this! Will try it out along with the 2.2.0 updates.

**Comment by nbouvrette** [comment]
@tappleby @mdvorak it took a bit longer than I was expecting but please give a try to the new [v3](https://github.com/Avansai/properties-file/releases/tag/3.0.0) release which has new editing capabilities and let me know what you think.

**Comment by tappleby** [comment]
@nbouvrette Great work! was able to clean up some of the custom parsing in our app. I ended up with a custom util script that may be useful for some:

```ts
import type { PropertiesEditor, InsertOptions } from 'properties-file/editor';

export function insertOrEdit(properties: PropertiesEditor, key: string, value: string, options?: Omit<InsertOptions, 'referenceKey' | 'position'>) {
  if (properties.keyLineNumbers[key]) {
    properties.edit(key, {
      newValue: value,
      newComment: options?.comment,
      commentDelimiter: options?.commentDelimiter,
      separator: options?.separator,
      escapeUnicode: options?.escapeUnicode
    });
  } else {
    properties.insert(key, value, options);
  }
}
```

**Comment by nbouvrette** [comment]
Thanks for sharing @tappleby - I hesitated to add an `upsert` method because I thought "nobody would use it" but I guess I was wrong.

Feel free to upgrade to 3.1 which was just released, you can now use the `upsert` method directly and clean up more custom code! Note that I made other naming changes to have more consistent APIs, so please check the release notes (it should be very quick to change)

Please open new issues if you have ideas on how to improve the editor - I personally don't use it for any of my projects, so hopefully, the APIs I came up with will make sense.
