### ISSUE TITLE
Getting value for a key

### ISSUE THREAD

**Issue by Joothi** [Avansai/properties-file#20]
In Java , we can use Property.getproperty("key") to get the value but here we are in a position to iterate the collection to fetch a value. 
Is there any similar method or I should role back to V2 to achieve the same?

**Comment by nbouvrette** [comment]
Hi @Joothi,

I'm not sure I understand your use case - are you simply trying to read the content of a `.properties` file and access the value of a key?

Have you considered using `getProperties` for example if you look at the readme you could do this:

```ts
import { readFileSync } from 'node:fs'
import { getProperties } from 'properties-file'

const properties = getProperties(readFileSync('hello-world.properties'))

console.log(properties)
console.log(`"hello" key value: ${properties['hello']}`)
```

Which would output:

```sh
{ hello: 'hello', world: 'world' }
"hello" key value: hello
```

**Comment by nbouvrette** [comment]
I'm going to close this for now. Let me know if my comment did not answer your question.
